graph TD;


Assets-->Art;
Assets-->Level;
Assets-->Resources; %%{only_put_assets_here_when_discussed}%%
Assets-->Scripts;
Assets-->TextMeshPro;

Art-->Animations;
Art-->Fonts;
Art-->CharacterSprites
Art-->Headshots
Art-->Props
Art-->TileMap
Art-->UI

Animations-->Characters;

Characters-->Npcs;
Characters-->Takkie;
Characters-->Siepie;

Npcs-->DJacky;
Npcs-->Evy;
Npcs-->Jade;
Npcs-->Ryan;

Takkie-->TakkieAnimation[Sheets];
Siepie-->SiepieAnimation[Sheets];

Level-->Prefabs;
Level-->Scenes;